name: Run Crawler
on:
  schedule:
    # 日本の月曜の2時から
    - cron: '0 17 * * 0'
jobs:
  run_crawler:
    runs-on: ubuntu-latest
    env:
      ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      ACCESS_KEY_SECRET:  ${{ secrets.ACCESS_KEY_SECRET }}
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - run: yarn install
    - run: node crawler.js
    - uses: gautamkrishnar/keepalive-workflow@master # using the workflow with default settings
