name: Run Crawler
on:
  schedule:
    - cron: '0 3 * * 1'
jobs:
  run_crawler:
    runs-on: ubuntu-latest
    env:
      ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      ACCESS_KEY_SECRET:  ${{ secrets.ACCESS_KEY_SECRET }}
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - run: yarn install
    - run: node crawler.js