name: Run Crawler
on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Are you sure?'     
        required: true
        default: 'yes'
jobs:
  run_crawler:
    runs-on: ubuntu-latest
    env:
      ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      ACCESS_KEY_SECRET:  ${{ secrets.ACCESS_KEY_SECRET }}
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - run: yarn install
    - run: node crawler.js